### ISSUE TITLE
Scala 3 support?

### ISSUE THREAD

**Issue by SethTisue** [twitter/algebird#1099]
perhaps a volunteer would like to tackle this?

note that algebird-core/src/main/scala/com/twitter/algebird/macros is 288 lines of code — 288 is not zero, but it's a not a huge number either

**Comment by SethTisue** [comment]
@regadas @johnynek are you, is somebody, still able to merge PRs here?

**Comment by johnynek** [comment]
With all the changes at Twitter I'm not sure. 

I used to be.

The macros are just derivation macros I believe, so they should be quite straightforward.

**Comment by johnynek** [comment]
I just merged a PR, so yes, I can merge PRs.

**Comment by BusyByte** [comment]
@johnynek was just looking for a Scala 3 release of algebird core, is that Scala 3 pr ready?

**Comment by SethTisue** [comment]
perhaps Typelevel folks (e.g. on #general-dev in the Typelevel Discord) would like to put the word out that #1105 has stalled and volunteers are needed to get it moving again

**Comment by johnynek** [comment]
I think I'm still able to merge PRs but yeah that PR seems to have merge conflicts.

If we can get a green PR without breaking mima for existing versions that would be ideal.

**Comment by regadas** [comment]
I can help as well... just ping me. I might still have a look at it's current state

**Comment by mullerhai** [comment]
> I can help as well... just ping me. I might still have a look at it's current state

HI， could you do support  release this project to scala3 ，thanks

**Comment by mullerhai** [comment]
> I think I'm still able to merge PRs but yeah that PR seems to have merge conflicts.
> 
> If we can get a green PR without breaking mima for existing versions that would be ideal.

I  think   on 2025   we need release scala3  ,no matter  the twtter boss  Mask mask so bad hurt  the code team

**Comment by mullerhai** [comment]
> perhaps Typelevel folks (e.g. on #general-dev in the Typelevel Discord) would like to put the word out that [#1105](https://github.com/twitter/algebird/pull/1105) has stalled and volunteers are needed to get it moving again

please  make in release to scala3 , so many  code and project need it,thanks
